---
title:               <%= ENV['OBTVSE_TITLE'] %>
tagline:             <%= ENV['OBTVSE_TAGLINE'] %>
login:               <%= ENV["OBTVSE_LOGIN"] %>
password:            <%= ENV["OBTVSE_PASSWORD"] %>
name:                <%= ENV['OBTVSE_NAME'] %>
twitter:             <%= ENV['OBTVSE_TWITTER'] %>
github:              <%= ENV['OBTVSE_GITHUB'] %>
email:               <%= ENV['OBTVSE_EMAIL'] %>
google_analytics_id: <%= ENV['OBTVSE_GOOGLE_ANALYTICS_ID'] %>
disqus_shortname:    <%= ENV.fetch("DISQUS_SHORTNAME") { "" } %>
